title: Synus
email: info@synus.org
description: >- # this means to ignore newlines until "baseurl:"
  Making software sustainable
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.synus.org" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  synus-org

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
